contactTab <- tabItem(tabName = "contact",
                      fluidRow(
                        column(4, offset=1, 
                               h4("Samuel Bharti"),
                               h6("Role: Project Technical Lead"),
                               h6(img(src = "email.png", height = 30, width = 30), "-"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), "-"),
                               br(),
                               h4("Disha Chauhan"),
                               h6("Role: Project Management Lead; Groups A, B1, D Manager"),
                               h6(img(src = "email.png", height = 30, width = 30), "1chopin@gmail.com"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("https://www.linkedin.com/in/disha-chauhan-2749621b0/",
                                    href = "https://www.linkedin.com/in/disha-chauhan-2749621b0/")),
                               br(),
                               h4("Austin Yang"),
                               h6("Role: Project Management Lead"),
                               h6(img(src = "email.png", height = 30, width = 30), "-"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("-")),
                               br(),
                               h4("Nikita Krishnan"),
                               h6("Role: Groups A and B1 Manager, "),
                               h6(img(src = "email.png", height = 30, width = 30), "-"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("www.linkedin.com/in/nikita-krishnan",
                                    href = "www.linkedin.com/in/nikita-krishnan")),
                               br(),
                               h4("Shreya Vora"),
                               h6("Role: Groups B1 Manager, "),
                               h6(img(src = "email.png", height = 30, width = 30), "-"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("-"))),
                        
                        column(4, offset = 2,
                               h4("Arian Veyssi"),
                               h6("Role: Bioinformatics Project Lead, Group B2 Manager"),
                               h6(img(src = "email.png", height = 30, width = 30), "veyssi20@gmail.com"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("https://www.linkedin.com/in/arian-veyssi-558446218/",
                                    href = "https://www.linkedin.com/in/arian-veyssi-558446218/")),
                               br(),
                               h4("Roman Ramirez"),
                               h6("Role: Group B2 Manager"),
                               h6(img(src = "email.png", height = 30, width = 30), "rr8rk@virginia.edu"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("https://www.linkedin.com/in/roman-h-ramirez/",
                                    href = "https://www.linkedin.com/in/roman-h-ramirez/")),
                               br(),
                               h4("Hou Wang (Ivan) Lam"),
                               h6("Role: Bioinformatics Project Lead, Group B2 Participant"),
                               h6(img(src = "email.png", height = 30, width = 30), "ivan_lam_27@hotmail.com"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("https://www.linkedin.com/in/hou-wang-ivan-lam-56867a18b/",
                                    href = "https://www.linkedin.com/in/hou-wang-ivan-lam-56867a18b/")),
                               br(),
                               h4("Aditi Verma"),
                               h6("Role: Group C Manager"),
                               h6(img(src = "email.png", height = 30, width = 30), "aditi.verma.av19@gmail.com"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("-")),
                               br(),
                               h4("Huikun (Kelly) Li"),
                               h6("Role: Group D Manager"),
                               h6(img(src = "email.png", height = 30, width = 30), "huikun321@gmail.com"),
                               h6(img(src = "linkedin.png", height = 30, width = 30), 
                                  a("https://www.linkedin.com/in/kelly-li-b149b2218/",
                                    href = "https://www.linkedin.com/in/kelly-li-b149b2218/"))
                          )
                       )
                       )
                        
                      
